# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(667, 607)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(67, 67, 67);"))
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 641, 581))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.show_train_set_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.show_train_set_button.setEnabled(False)
        self.show_train_set_button.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);\n"
"background-color: rgb(96, 96, 96);"))
        self.show_train_set_button.setObjectName(_fromUtf8("show_train_set_button"))
        self.horizontalLayout.addWidget(self.show_train_set_button)
        self.show_membership_functions_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.show_membership_functions_button.setEnabled(False)
        self.show_membership_functions_button.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);\n"
"background-color: rgb(96, 96, 96);"))
        self.show_membership_functions_button.setObjectName(_fromUtf8("show_membership_functions_button"))
        self.horizontalLayout.addWidget(self.show_membership_functions_button)
        self.show_rules_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.show_rules_button.setEnabled(False)
        self.show_rules_button.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);\n"
"background-color: rgb(96, 96, 96);"))
        self.show_rules_button.setObjectName(_fromUtf8("show_rules_button"))
        self.horizontalLayout.addWidget(self.show_rules_button)
        self.gridLayout.addLayout(self.horizontalLayout, 13, 0, 1, 3)
        self.browse_button = QtGui.QToolButton(self.gridLayoutWidget)
        self.browse_button.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);\n"
"background-color: rgb(96, 96, 96);"))
        self.browse_button.setObjectName(_fromUtf8("browse_button"))
        self.gridLayout.addWidget(self.browse_button, 2, 2, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.train_to_test_ratio_slider = QtGui.QSlider(self.gridLayoutWidget)
        self.train_to_test_ratio_slider.setStyleSheet(_fromUtf8(""))
        self.train_to_test_ratio_slider.setMinimum(5)
        self.train_to_test_ratio_slider.setMaximum(100)
        self.train_to_test_ratio_slider.setProperty("value", 50)
        self.train_to_test_ratio_slider.setOrientation(QtCore.Qt.Horizontal)
        self.train_to_test_ratio_slider.setObjectName(_fromUtf8("train_to_test_ratio_slider"))
        self.horizontalLayout_3.addWidget(self.train_to_test_ratio_slider)
        self.train_to_test_ratio_spinbox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.train_to_test_ratio_spinbox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.train_to_test_ratio_spinbox.setMinimum(5)
        self.train_to_test_ratio_spinbox.setMaximum(100)
        self.train_to_test_ratio_spinbox.setProperty("value", 50)
        self.train_to_test_ratio_spinbox.setObjectName(_fromUtf8("train_to_test_ratio_spinbox"))
        self.horizontalLayout_3.addWidget(self.train_to_test_ratio_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 3)
        self.dataset_path_input = QtGui.QLineEdit(self.gridLayoutWidget)
        self.dataset_path_input.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.dataset_path_input.setObjectName(_fromUtf8("dataset_path_input"))
        self.gridLayout.addWidget(self.dataset_path_input, 2, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.testing_section_label = QtGui.QLabel(self.gridLayoutWidget)
        self.testing_section_label.setStyleSheet(_fromUtf8("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(233, 233, 233);\n"
""))
        self.testing_section_label.setObjectName(_fromUtf8("testing_section_label"))
        self.gridLayout.addWidget(self.testing_section_label, 19, 0, 1, 1)
        self.train_to_test_ratio_label = QtGui.QLabel(self.gridLayoutWidget)
        self.train_to_test_ratio_label.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);"))
        self.train_to_test_ratio_label.setAlignment(QtCore.Qt.AlignCenter)
        self.train_to_test_ratio_label.setObjectName(_fromUtf8("train_to_test_ratio_label"))
        self.gridLayout.addWidget(self.train_to_test_ratio_label, 4, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 31, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 15, 0, 1, 1)
        self.characteristics_label = QtGui.QLabel(self.gridLayoutWidget)
        self.characteristics_label.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);"))
        self.characteristics_label.setAlignment(QtCore.Qt.AlignCenter)
        self.characteristics_label.setObjectName(_fromUtf8("characteristics_label"))
        self.gridLayout.addWidget(self.characteristics_label, 24, 0, 1, 3)
        self.training_section_label = QtGui.QLabel(self.gridLayoutWidget)
        self.training_section_label.setStyleSheet(_fromUtf8("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(233, 233, 233);"))
        self.training_section_label.setObjectName(_fromUtf8("training_section_label"))
        self.gridLayout.addWidget(self.training_section_label, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 18, 0, 1, 3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.first_input = QtGui.QLineEdit(self.gridLayoutWidget)
        self.first_input.setEnabled(False)
        self.first_input.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.first_input.setObjectName(_fromUtf8("first_input"))
        self.horizontalLayout_2.addWidget(self.first_input)
        self.second_input = QtGui.QLineEdit(self.gridLayoutWidget)
        self.second_input.setEnabled(False)
        self.second_input.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.second_input.setObjectName(_fromUtf8("second_input"))
        self.horizontalLayout_2.addWidget(self.second_input)
        self.third_input = QtGui.QLineEdit(self.gridLayoutWidget)
        self.third_input.setEnabled(False)
        self.third_input.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.third_input.setObjectName(_fromUtf8("third_input"))
        self.horizontalLayout_2.addWidget(self.third_input)
        self.fourth_input = QtGui.QLineEdit(self.gridLayoutWidget)
        self.fourth_input.setEnabled(False)
        self.fourth_input.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.fourth_input.setObjectName(_fromUtf8("fourth_input"))
        self.horizontalLayout_2.addWidget(self.fourth_input)
        self.gridLayout.addLayout(self.horizontalLayout_2, 30, 0, 1, 3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.first_label = QtGui.QLabel(self.gridLayoutWidget)
        self.first_label.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);"))
        self.first_label.setObjectName(_fromUtf8("first_label"))
        self.horizontalLayout_5.addWidget(self.first_label)
        self.second_label = QtGui.QLabel(self.gridLayoutWidget)
        self.second_label.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);"))
        self.second_label.setObjectName(_fromUtf8("second_label"))
        self.horizontalLayout_5.addWidget(self.second_label)
        self.third_label = QtGui.QLabel(self.gridLayoutWidget)
        self.third_label.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);"))
        self.third_label.setObjectName(_fromUtf8("third_label"))
        self.horizontalLayout_5.addWidget(self.third_label)
        self.fourth_label = QtGui.QLabel(self.gridLayoutWidget)
        self.fourth_label.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);"))
        self.fourth_label.setObjectName(_fromUtf8("fourth_label"))
        self.horizontalLayout_5.addWidget(self.fourth_label)
        self.gridLayout.addLayout(self.horizontalLayout_5, 25, 0, 1, 3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.classify_sample_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.classify_sample_button.setEnabled(False)
        self.classify_sample_button.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);\n"
"background-color: rgb(96, 96, 96);"))
        self.classify_sample_button.setObjectName(_fromUtf8("classify_sample_button"))
        self.horizontalLayout_6.addWidget(self.classify_sample_button)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_6, 32, 0, 1, 3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.classify_test_set_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.classify_test_set_button.setEnabled(False)
        self.classify_test_set_button.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);\n"
"background-color: rgb(96, 96, 96);"))
        self.classify_test_set_button.setObjectName(_fromUtf8("classify_test_set_button"))
        self.horizontalLayout_4.addWidget(self.classify_test_set_button)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_4, 20, 0, 1, 3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setMargin(11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.train_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.train_button.setEnabled(True)
        self.train_button.setStyleSheet(_fromUtf8("color: rgb(233, 233, 233);\n"
"background-color: rgb(96, 96, 96);"))
        self.train_button.setObjectName(_fromUtf8("train_button"))
        self.horizontalLayout_7.addWidget(self.train_button)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout_7, 7, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.show_train_set_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Show the train set</span></p></body></html>", None))
        self.show_train_set_button.setText(_translate("MainWindow", "Show Train Set", None))
        self.show_membership_functions_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Show the membeship fuctions created by the training</span></p></body></html>", None))
        self.show_membership_functions_button.setText(_translate("MainWindow", "Show Membership Functions", None))
        self.show_rules_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Show the rules created by the training</span></p></body></html>", None))
        self.show_rules_button.setText(_translate("MainWindow", "Show Rules", None))
        self.browse_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Select the dataset used for training</span></p></body></html>", None))
        self.browse_button.setText(_translate("MainWindow", "Browse", None))
        self.train_to_test_ratio_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Adjust the train to test ratio</span></p></body></html>", None))
        self.train_to_test_ratio_spinbox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Adjust the train to test ratio</span></p></body></html>", None))
        self.dataset_path_input.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">The dataset path</span></p></body></html>", None))
        self.testing_section_label.setText(_translate("MainWindow", "Testing Section", None))
        self.train_to_test_ratio_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Train to Test Ratio</span></p></body></html>", None))
        self.characteristics_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Characteristics</span></p></body></html>", None))
        self.training_section_label.setText(_translate("MainWindow", "Training Section", None))
        self.first_input.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">The first parameter of a sample</span></p></body></html>", None))
        self.second_input.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">The second parameter of a sample</span></p></body></html>", None))
        self.third_input.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">The third parameter of a sample</span></p></body></html>", None))
        self.fourth_input.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">The fourth parameter of a sample</span></p></body></html>", None))
        '''
        self.first_label.setText(_translate("MainWindow", "1st", None))
        self.second_label.setText(_translate("MainWindow", "2nd", None))
        self.third_label.setText(_translate("MainWindow", "3rd", None))
        self.fourth_label.setText(_translate("MainWindow", "4th", None))
        '''
        self.classify_sample_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Classify a sample using the above inputs as parameters</span></p></body></html>", None))
        self.classify_sample_button.setText(_translate("MainWindow", "Classify Sample", None))
        self.classify_test_set_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Classify the samples inside the test set</span></p></body></html>", None))
        self.classify_test_set_button.setText(_translate("MainWindow", "Classify Test Set", None))
        self.train_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Begin the training of the model</span></p></body></html>", None))
        self.train_button.setText(_translate("MainWindow", "Train", None))

